import json
import asyncio
from datetime import datetime, timezone
import urllib.parse

from playwright.async_api import async_playwright

DEALERS_TO_SCRAPE = ['theonewatches', 'trusty-time']
OUT_CATALOG = 'dealer-catalog.json'

def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def tokenize(s):
    if not s: return []
    import re
    tokens = re.split(r'[\s,\/\-()[\]{}]+', str(s).lower())
    tokens = [re.sub(r'[^\w]', '', t) for t in tokens]
    return [t for t in tokens if len(t) >= 2 or t.isdigit()]

def primary_sku_token(ref_tokens):
    import re
    mixed = [t for t in ref_tokens if re.search(r'[a-z]', t) and re.search(r'\d', t) and re.search(r'\d{3,}', t)]
    if mixed: return sorted(mixed, key=lambda x: (-len(x), x))[0]
    numeric = [t for t in ref_tokens if re.match(r'^\d{3,}$', t)]
    if numeric: return sorted(numeric, key=lambda x: (-len(x), x))[0]
    return None

async def scrape_dealer(context, dealer_id, search_url):
    page = await context.new_page()
    try:
        await page.goto(search_url, timeout=15000)
        # Handle OpenCart (theonewatches)
        if dealer_id == 'theonewatches':
            await page.wait_for_selector('.product-layout', timeout=5000)
            items = await page.query_selector_all('.product-layout')
            if items:
                first = items[0]
                url_el = await first.query_selector('.name a')
                url = await url_el.get_attribute('href')
                title = await url_el.inner_text()
                price_el = await first.query_selector('.price')
                price_text = await price_el.inner_text() if price_el else ""
                import re
                price_match = re.search(r'\$(\d+(?:\.\d+)?)', price_text)
                price = float(price_match.group(1)) if price_match else 0
                img_el = await first.query_selector('.image img')
                img_url = await img_el.get_attribute('src') if img_el else ""
                return {
                    "url": url,
                    "title": title.strip(),
                    "price": price,
                    "currency": "USD",
                    "in_stock": True,
                    "images": [img_url] if img_url else []
                }
        # Handle Zen Cart (trusty-time)
        elif dealer_id == 'trusty-time':
            await page.wait_for_selector('.centerBoxContentsProducts', timeout=5000)
            items = await page.query_selector_all('.centerBoxContentsProducts')
            if items:
                first = items[0]
                url_el = await first.query_selector('.itemTitle a')
                url = await url_el.get_attribute('href') if url_el else ""
                title = await url_el.inner_text() if url_el else ""
                price_el = await first.query_selector('.normalprice')
                price_text = await price_el.inner_text() if price_el else ""
                import re
                price_match = re.search(r'\$(\d+(?:\.\d+)?)', price_text)
                price = float(price_match.group(1)) if price_match else 0
                img_el = await first.query_selector('.image img')
                img_url = await img_el.get_attribute('src') if img_el else ""
                return {
                    "url": url,
                    "title": title.strip(),
                    "price": price,
                    "currency": "USD",
                    "in_stock": True,
                    "images": [img_url] if img_url else []
                }
    except Exception as e:
        print(f"Error scraping {search_url}: {e}")
    finally:
        await page.close()
    return None

async def scrape_with_semaphore(semaphore, context, d_id, search_url, watch_id, catalog):
    async with semaphore:
        offer = await scrape_dealer(context, d_id, search_url)
        if offer:
            offer['scraped_at'] = catalog['scraped_at']
            print(f"Found offer for {watch_id} at {d_id}: ${offer['price']}")
            return watch_id, d_id, offer
        return watch_id, d_id, None

async def main():
    guide = load_json('who-makes-the-best-guide.json')
    search_templates = load_json('dealer-search.json')
    
    catalog = {
        "_doc": "Auto-generated by the catalog scraper. Re-run weekly via GitHub Action.",
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "offers": {}
    }

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(user_agent="Mozilla/5.0 reptime-catalog-scraper")

        watches = guide.get("watches", [])
        print(f"Found {len(watches)} watches in guide.")
        watches_to_scrape = watches
        
        semaphore = asyncio.Semaphore(10)
        tasks = []
        
        for w in watches_to_scrape:
            brand = str(w.get('brand', '')).lower().replace(r'[^a-z0-9]', '')
            family = str(w.get('model_family', '')).lower()
            ref = str(w.get('reference', ''))
            
            import re
            slugify = lambda s: re.sub(r'^-+|-+$', '', re.sub(r'[^a-z0-9]+', '-', str(s or '').lower()))
            watch_id = f"{slugify(brand)}-{slugify(family)}-{slugify(ref or 'any')}"
            
            ref_tokens = tokenize(ref)
            sku = primary_sku_token(ref_tokens)
            q = sku if sku else f"{w.get('brand','')} {w.get('model_family','')}".strip()
            if not q: continue
            
            for d_id in DEALERS_TO_SCRAPE:
                tmpl = search_templates.get(d_id, {}).get('template')
                if not tmpl: continue
                search_url = tmpl.replace('{q}', urllib.parse.quote(q))
                tasks.append(scrape_with_semaphore(semaphore, context, d_id, search_url, watch_id, catalog))
                
        print(f"Starting {len(tasks)} parallel scraping tasks...")
        results = await asyncio.gather(*tasks)
        
        for watch_id, d_id, offer in results:
            if offer:
                if watch_id not in catalog['offers']:
                    catalog['offers'][watch_id] = {}
                catalog['offers'][watch_id][d_id] = offer

        await browser.close()

    with open(OUT_CATALOG, 'w', encoding='utf-8') as f:
        json.dump(catalog, f, indent=2)
    print(f"Saved {len(catalog['offers'])} watches to {OUT_CATALOG}")

if __name__ == "__main__":
    asyncio.run(main())
